#!/bin/sh -x

FW=/Library/Frameworks/Mono.framework
FW_CURRENT=${FW}/Versions/Current

# Remove /usr/bin/pkg-config if it's a symlink to the Mono-installed one
PKG_CONFIG_LINK="/usr/bin/pkg-config"
if [ -L $PKG_CONFIG_LINK ]; then
    location=`readlink $PKG_CONFIG_LINK`
    case "$location" in
    *Mono.framework*) rm $PKG_CONFIG_LINK;;
    esac
fi

WHITELIST=$(cat "$(dirname "$0")/whitelist.txt")

if [ -d ${FW}/Commands ]; then
    for i in ${WHITELIST}; do
	# Only create a symlink if there isn't a file there
	if test -e "${FW}/Commands/${i}" && test ! -e "/usr/bin/${i}"; then
        	echo "${i}"
	        ln -sf "${FW}/Commands/${i}" "/usr/bin/${i}"
	fi
    done;
else
    echo "${FW}/Commands does not exist"
    echo "Can not create links to /usr/bin."
fi

if [ -d ${FW_CURRENT} ]; then
    cd ${FW_CURRENT}/share/man
    for i in ${WHITELIST}; do
        for j in $(ls man*/${i}.*); do
            if test ! -e "/usr/share/man/${j}"; then
                ln -sf "${FW_CURRENT}/share/man/${j}" "/usr/share/man/${j}"
            fi
        done
    done

    cd ${FW_CURRENT}/etc
    # Make sure we run the files we lay down, and not other stuff installed on the system
    export PATH=${FW_CURRENT}/bin:$PATH
    # gtk+ setup
    gdk-pixbuf-query-loaders --update-cache
    # pango setup
    mkdir -p pango
    pango-querymodules >  pango/pango.modules
fi

# Delete older Monos
#
# - keep if 'Versions/x.y.z/keep' exists
# - Keep if it is greater than $CURRENT_VER
#
CURRENT=`basename $(readlink ${FW_CURRENT})`
echo "Current:" $CURRENT

pushd ${FW}/Versions
for i in `ls -d *`; do
    if [ -f $i/keep ]; then
        echo "Keeping" $i
        continue
    fi

    # A magical bit of Perl: http://stackoverflow.com/a/7366753/494990
    result=$(perl -e 'print shift cmp shift' $i $CURRENT)
    if [ $result -ge 0 ]; then
        echo "Skipping" $i
        continue

    else
        echo "rm -rf" $i
        rm -rf $i
    fi
done
popd

# Mono framework should be owned by root
chown -R root:admin ${FW}
